In [20]:
import pandas as pd
import sqlalchemy as db

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

from dotenv import load_dotenv
import os

load_dotenv("../configuration/.env")

True

In [26]:
def connect_to_mysql(database):
    username = os.getenv('MYSQL_USER')
    password = os.getenv('MYSQL_PASSWORD')
    host = os.getenv('MYSQL_HOST')
    port = os.getenv('MYSQL_PORT')
    uri = f"mysql://{username}:{password}@{host}/{database}"
    print(uri)
    return db.create_engine(uri)

def connect_to_mongo():
    username = os.getenv('MONGODB_USERNAME')
    password = os.getenv('MONGODB_PASSWORD')
    host = os.getenv('MONGODB_HOST')
    database = os.getenv('MONGODB_CLUSTER_NAME')
    uri = f"mongodb+srv://{username}:{password}@{host}?appName={database}"
    print(uri)
    return MongoClient(uri, server_api=ServerApi('1'))

# Data Warehouse Connection

In [27]:
# connect to MySQL database data warehouse
dw_engine = connect_to_mysql(os.getenv('MYSQL_DATABASE_DW'))

mysql://root:@localhost/dw_netflix

# EXTRACT STAGE

## MYSQL OLTP

In [28]:
# connect to MySQL OLTP
connection_OLTP = connect_to_mysql(os.getenv('MYSQL_DATABASE_OLTP'))

mysql://root:@localhost/db_movies_netflix_transact

In [29]:
# SQL query to retrieve movie details along with their genre and participants (actors, directors, etc.)
query = """
SELECT
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate,
    genre.name as genre, person.name as participantName, performer.performerRole as performerRole
FROM movie
INNER JOIN performer ON movie.movieID=performer.movieID
INNER JOIN person ON person.personID = performer.personID
INNER JOIN movie_genre ON movie.movieID = movie_genre.movieID
INNER JOIN genre ON movie_genre.genreID = genre.genreID
"""

# Execute the SQL query and load the result into a DataFrame
df_movies_oltp = pd.read_sql(query, con=connection_OLTP)

# Display the DataFrame with movie details
df_movies_oltp.head()

,movieID,title,releaseDate,genre,participantName,performerRole
0,M009,Braveheart,1995-05-24,Action,Tom Hanks,Actor
1,M009,Braveheart,1995-05-24,Action,Steven Spielberg,Director
2,M011,The Dark Knight,2008-07-18,Action,Johnny Depp,Actor
3,M011,The Dark Knight,2008-07-18,Action,Christopher Nolan,Director
4,M014,Avatar,2009-12-18,Action,Leonardo DiCaprio,Actor

## MongoDB

In [30]:
# conexion a mongo
clientMongo = connect_to_mongo()

mongodb+srv://joagzb:VxQyRa4Kkz9l7ndd@cluster0.us92mpj.mongodb.net/?appName=Cluster0

In [31]:
# Access the database
dbMongo = clientMongo['netflix_movies']

# Access the collections
movies = dbMongo['movies_df']
movies_documents = list(movies.find())
df_movies = pd.DataFrame(movies_documents)

interactions = dbMongo['user_netflix_interactions']
interactions_documents = list(interactions.find())
df_interactions = pd.DataFrame(interactions_documents)

df_movies.info()
df_interactions.info()
print("-------------")
print(df_movies.head())
print("-------------")
print(df_interactions.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9125 entries, 0 to 9124
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _id                   9125 non-null   object
 1   title                 9124 non-null   object
 2   gender                9125 non-null   object
 3   releaseDate           9125 non-null   object
 4   AwardMovie            9125 non-null   object
 5   netflix_score         7322 non-null   float64
 6   imdb_score            7309 non-null   float64
 7   sensacine_score       7360 non-null   float64
 8   rottentomatoes_score  7286 non-null   float64
dtypes: float64(4), object(5)
memory usage: 641.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9125 entries, 0 to 9124
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   _id                  9125 non-null   object
 1   user                 9125 non-null   object
 2   movieTitle           9124 non-null   object
 3   finishCount          9125 non-null   int64
 4   backClickCount       9125 non-null   int64
 5   movieForwardCount    9125 non-null   int64
 6   playCount            9125 non-null   int64
 7   movieViewPercentage  9125 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 570.4+ KB
-------------
                        _id  \
0  66836bf21e67c1c81c3ca441
1  66836bf21e67c1c81c3ca444
2  66836bf21e67c1c81c3ca447
3  66836bf21e67c1c81c3ca449
4  66836bf21e67c1c81c3ca44b

                                               title     gender releaseDate  \
0                            Birth of a Nation, The       Drama  1915-01-01
1                                    Immigrant, The      Comedy  1917-01-01
2  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...      Crime  1920-01-01
3                                Mark of Zorro, The   Adventure  1920-01-01
4                                Haunted House, The      Comedy  1921-01-01

  AwardMovie  netflix_score  imdb_score  sensacine_score  rottentomatoes_score
0   Sin Info            2.0         4.0              1.0                   5.0
1   Sin Info            NaN         3.0              2.0                   2.0
2   Sin Info            NaN         3.0              2.0                   3.0
3   Sin Info            3.0         NaN              5.0                   2.0
4   Sin Info            NaN         3.0              1.0                   NaN
-------------
                        _id     user  \
0  66836bc21e67c1c81c3c80a1  user_25
1  66836bc21e67c1c81c3c80a2   user_6
2  66836bc21e67c1c81c3c80a4  user_20
3  66836bc21e67c1c81c3c80a7   user_1
4  66836bc21e67c1c81c3c80a8  user_26

                                          movieTitle  finishCount  \
0                                Billy Blazes, Esq.             2
1  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...            1
2                                Mark of Zorro, The             2
3                                         Goat, The             2
4                                         Boat, The             2

   backClickCount  movieForwardCount  playCount  movieViewPercentage
0               2                  0          8               100.00
1               1                  3          2               100.00
2               1                  1          2                62.11
3               9                  1          2               100.00
4               0                  5          2                33.53

# TRANSFORM STAGE

## preprocess interactions and movies collections

In [32]:
df_movies = df_movies.rename(columns={"gender":"genre"}).reset_index(names="movieID").drop(columns=["_id"])
df_movies["movieID"] = df_movies["movieID"].astype(str)

df_interactions = df_interactions.drop(columns=["_id"]).reset_index(names="userID")

print(df_movies.columns)
print("-------------")
print(df_interactions.columns)

Index(['movieID', 'title', 'genre', 'releaseDate', 'AwardMovie',
       'netflix_score', 'imdb_score', 'sensacine_score',
       'rottentomatoes_score'],
      dtype='object')
-------------
Index(['userID', 'user', 'movieTitle', 'finishCount', 'backClickCount',
       'movieForwardCount', 'playCount', 'movieViewPercentage'],
      dtype='object')

 movies dataframes normalization

 movieIndex==permormerID

In [33]:
# add index so as to identify permormerID with a movie through movieIndex (later movieIndex==permormerID)
# here, df_movies_oltp is the only dataframe which contains performers
df_movies_oltp.reset_index(names="movieIndex", inplace=True)

## get users dimention

In [34]:
df_dim_users = df_interactions[["userID","user"]].copy()
df_dim_users = df_dim_users.rename(columns={"user": "username"})
df_dim_users.head()

   userID username
0       0  user_25
1       1   user_6
2       2  user_20
3       3   user_1
4       4  user_26

## get interactions dimention

"userID"=="interactionID"

In [35]:
df_dim_interactions = df_interactions.copy().rename(columns={"userID":"interactionID"}).drop(columns=["movieTitle","user"])
df_dim_interactions.head()

,interactionID,finishCount,backClickCount,movieForwardCount,playCount,movieViewPercentage
0,0,2,2,0,8,100.00
1,1,1,1,3,2,100.00
2,2,2,1,1,2,62.11
3,3,2,9,1,2,100.00
4,4,2,0,5,2,33.53

## movies dimention

In [36]:
# dataframe containing information fetched from mongo
df_dim_movies = df_movies[["movieID","title", "genre","releaseDate","AwardMovie"]].copy()
df_dim_movies = df_dim_movies.rename(columns={"AwardMovie":"award"})

# add to this dataframe from fetched from with df_movies_oltp at the end
df_movies_oltp["award"] = None
df_movies_oltp['releaseDate'] = df_movies_oltp['releaseDate'].astype(str)
df_dim_movies = pd.concat([df_dim_movies, df_movies_oltp], ignore_index=True,axis=0)
df_dim_movies.drop(columns=['performerRole','participantName','movieIndex'], inplace=True)

print(df_dim_movies.shape)
print(df_dim_movies.head())

(9183, 5)
  movieID                                              title      genre  \
0       0                            Birth of a Nation, The       Drama
1       1                                    Immigrant, The      Comedy
2       2  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...      Crime
3       3                                Mark of Zorro, The   Adventure
4       4                                Haunted House, The      Comedy

  releaseDate     award
0  1915-01-01  Sin Info
1  1917-01-01  Sin Info
2  1920-01-01  Sin Info
3  1920-01-01  Sin Info
4  1921-01-01  Sin Info

## performers dimention

In [38]:
df_dim_performers = df_movies_oltp[["movieIndex","participantName","performerRole"]].copy()
df_dim_performers.rename(columns={
  "movieIndex":"performerID",
  "participantName":"name",
  "performerRole":"role",
}, inplace=True)

print(df_dim_performers.shape)
print(df_dim_performers.columns)

(58, 3)
Index(['performerID', 'name', 'role'], dtype='object')

## score dimention

In [39]:
df_dim_score = df_movies[["title","netflix_score","imdb_score","sensacine_score","rottentomatoes_score"]].copy()
df_dim_score = df_dim_score.reset_index(names="scoreID")

# Check for duplicates on a pivot table where the index is the title and the value is the number of times a movie title is repeated
duplicates = df_movies.pivot_table(index=['title'], aggfunc='size')
duplicates = duplicates[duplicates > 1]

print("Example Duplicated Movie:")
print("\n")
print(df_dim_score[df_dim_score['title']==duplicates.sort_index().head(1).index[0]])

# merge duplicated values keeping the maximum score if two movies have the same title and different scores
df_dim_score = df_movies.groupby('title').agg({
    'netflix_score': 'max',
    'imdb_score': 'max',
    'sensacine_score': 'max',
    'rottentomatoes_score': 'max'
}).reset_index()

# rename columns
df_dim_score.rename(columns={
    'netflix_score': 'netflixScore',
    'imdb_score': 'imdbScore',
    'sensacine_score': 'sensacineScore',
    'rottentomatoes_score': 'rottentomatoesScore'
},inplace=True)

# Reset the index and assign unique IDs
df_dim_score.reset_index(drop=True, inplace=True)
df_dim_score['scoreID'] = df_dim_score.index

#print a duplicated movie and its scores
print("\n")
print("\nAggregated Movies with Maximum Scores:\n")
print(df_dim_score[df_dim_score['title']==duplicates.sort_index().head(1).index[0]])

Example Duplicated Movie:


      scoreID          title  netflix_score  imdb_score  sensacine_score  \
674       674  12 Angry Men             NaN         1.0              4.0
4618     4618  12 Angry Men             2.0         4.0              2.0

      rottentomatoes_score
674                    3.0
4618                   4.0



Aggregated Movies with Maximum Scores:

            title  netflixScore  imdbScore  sensacineScore  \
30  12 Angry Men            2.0        4.0             4.0

    rottentomatoesScore  scoreID
30                  4.0       30

# LOAD STAGE

In [40]:
# check last movie id to avoid duplicated primary key error
query_last_movie_id = """
SELECT MAX(movieID) FROM dimmovie;
"""

last_movie_id_prefix = pd.read_sql(query_last_movie_id, con=dw_engine).iloc[0,0]
if last_movie_id_prefix is not None:
  df_dim_movies["movieID"] = last_movie_id_prefix + df_dim_movies["movieID"].astype(str)

df_dim_movies.drop_duplicates(subset=["movieID"], inplace=True)

# Load dimMovie data
df_dim_movies.to_sql('dimmovie', con=dw_engine, if_exists='append', index=False,index_label='movieID')

9155

In [41]:
query_last_user_id = """
SELECT MAX(userID) FROM dimuser;
"""

df_dim_users["userID"] = df_dim_users["userID"].astype(int)

last_user_id = pd.read_sql(query_last_user_id, con=dw_engine).iloc[0, 0]
if last_user_id is not None:
  last_user_id = int(last_user_id)
  df_dim_users["userID"] = df_dim_users["userID"] + last_user_id + 1

# Load dimUser data
df_dim_users.to_sql('dimuser', con=dw_engine, if_exists='append', index=False)

9125

In [42]:
query_last_interaction_id = """
SELECT MAX(interactionID) FROM diminteraction;
"""

df_dim_interactions["interactionID"] = df_dim_interactions["interactionID"].astype(int)

last_interaction_id = pd.read_sql(query_last_interaction_id, con=dw_engine).iloc[0, 0]
if last_interaction_id is not None:
  last_interaction_id = int(last_interaction_id)
  df_dim_interactions["interactionID"] = df_dim_interactions["interactionID"] + last_interaction_id + 1


# Load dimInteraction data
df_dim_interactions.to_sql('diminteraction', con=dw_engine, if_exists='append', index=False)

9125

In [43]:
query_last_score_id = """
SELECT MAX(scoreID) FROM dimscore;
"""

df_dim_score["scoreID"] = df_dim_score["scoreID"].astype(int)

last_score_id = pd.read_sql(query_last_score_id, con=dw_engine).iloc[0, 0]
if last_score_id is not None:
  last_score_id = int(last_score_id)
  df_dim_score["scoreID"] = df_dim_score["scoreID"] + last_score_id + 1

# Load dimScore data
df_dim_score[["scoreID","netflixScore","imdbScore","sensacineScore","rottentomatoesScore"]].to_sql('dimscore', con=dw_engine, if_exists='append', index=False)

8892

In [44]:
query_last_performer_id = """
SELECT MAX(performerID) FROM dimperformer;
"""

df_dim_performers["performerID"] = df_dim_performers["performerID"].astype(int)

last_performer_id = pd.read_sql(query_last_performer_id, con=dw_engine).iloc[0, 0]
if last_performer_id is not None:
  last_performer_id = int(last_performer_id)
  df_dim_performers["performerID"] = df_dim_performers["performerID"] + last_performer_id + 1

# Load performers data
df_dim_performers.to_sql('dimperformer', con=dw_engine, if_exists='append', index=False)

58

## prepare fact watch

In [60]:
# Map interactions to their users
df_fact_watchs =df_interactions[["userID","movieTitle","user"]].copy()

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9125, 3)

Index(['userID', 'movieTitle', 'user'], dtype='object')

### map users

In [61]:
# Map users to their IDs
df_dim_user = pd.read_sql('SELECT userID,username FROM dimuser', con=dw_engine)
df_fact_watchs= df_fact_watchs.merge(df_dim_user, on="userID")

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9125, 4)

Index(['userID', 'movieTitle', 'user', 'username'], dtype='object')

### map movies

In [62]:
# Map movies to their IDs

# df_dim_movie= pd.read_sql('SELECT movieID,title FROM dimmovie', con=dw_engine)
df_fact_watchs["movieTitle"] = df_fact_watchs["movieTitle"].str.lower()
df_dim_movies['title'] = df_dim_movies['title'].str.lower()
df_fact_watchs = df_fact_watchs.merge(df_dim_movies[['movieID','title']], left_on='movieTitle', right_on='title',how='left').drop(columns=['title'])

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9655, 5)

Index(['userID', 'movieTitle', 'user', 'username', 'movieID'], dtype='object')

### map performers

In [63]:
# Map performers to the movies they participate in
# keep in mind that we have defined movieIndex==permormerID before
df_dim_performers = df_movies_oltp.copy().drop(columns=['award','movieID','releaseDate', 'genre', 'participantName', 'performerRole'])
df_dim_performers.rename(columns={"movieIndex": "performerID"}, inplace=True)
df_dim_performers["performerID"] = df_dim_performers["performerID"].astype(str)
df_dim_performers['title'] = df_dim_performers['title'].str.lower()
df_dim_performers = df_dim_performers.merge(df_dim_movies[['movieID','title']], left_on='performerID', right_on='movieID').drop(columns=['movieID'])

print(df_dim_performers.info())
print(df_fact_watchs.info())

df_fact_watchs["movieID"] = df_fact_watchs["movieID"].astype(str)
df_fact_watchs = df_fact_watchs.merge(df_dim_performers, left_on="movieID", right_on="performerID", how="left")

print(df_fact_watchs.shape)
df_fact_watchs.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   performerID  58 non-null     object
 1   title_x      58 non-null     object
 2   title_y      58 non-null     object
dtypes: object(3)
memory usage: 1.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9655 entries, 0 to 9654
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   userID      9655 non-null   int64
 1   movieTitle  9654 non-null   object
 2   user        9655 non-null   object
 3   username    9655 non-null   object
 4   movieID     9655 non-null   object
dtypes: int64(1), object(4)
memory usage: 377.3+ KB
None
(9655, 8)

Index(['userID', 'movieTitle', 'user', 'username', 'movieID', 'performerID',
       'title_x', 'title_y'],
      dtype='object')

### score

In [64]:
# Map scores to their movies
df_dim_score['title'] = df_dim_score['title'].str.lower()
df_fact_watchs = df_fact_watchs.merge(df_dim_score, left_on='movieTitle', right_on='title').drop(columns=['title'])

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9662, 13)

Index(['userID', 'movieTitle', 'user', 'username', 'movieID', 'performerID',
       'title_x', 'title_y', 'netflixScore', 'imdbScore', 'sensacineScore',
       'rottentomatoesScore', 'scoreID'],
      dtype='object')

load fact watch

In [65]:
# Prepare FactWatchs DataFrame
df_fact_watchs = df_fact_watchs[['userID', 'movieID','performerID','scoreID']]
df_fact_watchs['interactionID'] = df_fact_watchs[['userID']]
df_fact_watchs['movieID'] = df_fact_watchs['movieID'].astype(str)
df_fact_watchs.reset_index(names='id', inplace=True)

# Load FactWatchs data
df_fact_watchs.to_sql('factwatchs', con=dw_engine, if_exists='append', index=False)

print("Data loaded successfully")

Data loaded successfully