In [1]:
import pandas as pd
import sys
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from dotenv import load_dotenv
import os
import sqlalchemy as db
load_dotenv("../configuration/.env")

# Move up one level to the project_root and then access src
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

# Data Warehouse Connection

In [2]:
username = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASSWORD')
host = os.getenv('MYSQL_HOST')
port = os.getenv('MYSQL_PORT')
database = os.getenv('MYSQL_DATABASE_DW')
uri = f"mysql://{username}:{password}@{host}/{database}"
print(uri)

dw_engine = db.create_engine(uri)

mysql://root:@localhost/dw_netflix

# EXTRACT STAGE

## MYSQL OLTP

In [3]:
username = os.getenv('MYSQL_USER')
password = os.getenv('MYSQL_PASSWORD')
host = os.getenv('MYSQL_HOST')
port = os.getenv('MYSQL_PORT')
database = os.getenv('MYSQL_DATABASE_OLTP')
uri = f"mysql://{username}:{password}@{host}/{database}"
print(uri)

connection_OLTP = db.create_engine(uri)

mysql://root:@localhost/db_movies_netflix_transact

In [4]:
# SQL query to retrieve movie details along with their genre and participants (actors, directors, etc.)
query = """
SELECT
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate,
    genre.name as genre, person.name as participantName, performer.performerRole as performerRole
FROM movie
INNER JOIN performer ON movie.movieID=performer.movieID
INNER JOIN person ON person.personID = performer.personID
INNER JOIN movie_genre ON movie.movieID = movie_genre.movieID
INNER JOIN genre ON movie_genre.genreID = genre.genreID
"""

# Execute the SQL query and load the result into a DataFrame
df_movies_oltp = pd.read_sql(query, con=connection_OLTP)

# Display the DataFrame with movie details
df_movies_oltp.head()

,movieID,title,releaseDate,genre,participantName,performerRole
0,M009,Braveheart,1995-05-24,Action,Tom Hanks,Actor
1,M009,Braveheart,1995-05-24,Action,Steven Spielberg,Director
2,M011,The Dark Knight,2008-07-18,Action,Johnny Depp,Actor
3,M011,The Dark Knight,2008-07-18,Action,Christopher Nolan,Director
4,M014,Avatar,2009-12-18,Action,Leonardo DiCaprio,Actor

## MongoDB

In [5]:
username = os.getenv('MONGODB_USERNAME')
password = os.getenv('MONGODB_PASSWORD')
host =os.getenv('MONGODB_HOST')
database =os.getenv('MONGODB_CLUSTER_NAME')
uri = f"mongodb+srv://{username}:{password}@{host}?appName={database}"
print(uri)

clientMongo = MongoClient(uri, server_api=ServerApi('1'))

def extract_mongo_data(collection_name):
    db = clientMongo['netflix_movies']
    collection = db[collection_name]
    documents = list(collection.find())
    return pd.DataFrame(documents)

mongodb+srv://joagzb:VxQyRa4Kkz9l7ndd@cluster0.us92mpj.mongodb.net/?appName=Cluster0

In [6]:
df_movies = extract_mongo_data('movies_df')
df_interactions = extract_mongo_data('user_netflix_interactions')

print(df_movies.head())
print("-------------")
print(df_interactions.head())

                        _id  \
0  66836bf21e67c1c81c3ca441
1  66836bf21e67c1c81c3ca444
2  66836bf21e67c1c81c3ca447
3  66836bf21e67c1c81c3ca449
4  66836bf21e67c1c81c3ca44b

                                               title     gender releaseDate  \
0                            Birth of a Nation, The       Drama  1915-01-01
1                                    Immigrant, The      Comedy  1917-01-01
2  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...      Crime  1920-01-01
3                                Mark of Zorro, The   Adventure  1920-01-01
4                                Haunted House, The      Comedy  1921-01-01

  AwardMovie  netflix_score  imdb_score  sensacine_score  rottentomatoes_score
0   Sin Info            2.0         4.0              1.0                   5.0
1   Sin Info            NaN         3.0              2.0                   2.0
2   Sin Info            NaN         3.0              2.0                   3.0
3   Sin Info            3.0         NaN              5.0                   2.0
4   Sin Info            NaN         3.0              1.0                   NaN
-------------
                        _id     user  \
0  66836bc21e67c1c81c3c80a1  user_25
1  66836bc21e67c1c81c3c80a2   user_6
2  66836bc21e67c1c81c3c80a4  user_20
3  66836bc21e67c1c81c3c80a7   user_1
4  66836bc21e67c1c81c3c80a8  user_26

                                          movieTitle  finishCount  \
0                                Billy Blazes, Esq.             2
1  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...            1
2                                Mark of Zorro, The             2
3                                         Goat, The             2
4                                         Boat, The             2

   backClickCount  movieForwardCount  playCount  movieViewPercentage
0               2                  0          8               100.00
1               1                  3          2               100.00
2               1                  1          2                62.11
3               9                  1          2               100.00
4               0                  5          2                33.53

# TRANSFORM STAGE

## preprocess interactions and movies collections

In [7]:
movies = df_movies.copy()
interactions = df_interactions.copy()

movies = movies.rename(columns={"gender":"genre","title":"movieTitle"}).drop(columns=["_id"])
movies['title_lowercase'] = movies['movieTitle'].str.lower()

interactions = interactions.drop(columns=["_id"])
interactions['title_lowercase'] = interactions['movieTitle'].str.lower()

print(movies.shape)
print(movies.columns)
print("-----------")
print(interactions.shape)
print(interactions.columns)

(9125, 9)
Index(['movieTitle', 'genre', 'releaseDate', 'AwardMovie', 'netflix_score',
       'imdb_score', 'sensacine_score', 'rottentomatoes_score',
       'title_lowercase'],
      dtype='object')
-----------
(9125, 8)
Index(['user', 'movieTitle', 'finishCount', 'backClickCount',
       'movieForwardCount', 'playCount', 'movieViewPercentage',
       'title_lowercase'],
      dtype='object')

 ## movies_oltp dataframes preprocess

In [8]:
movies_oltp = df_movies_oltp.copy()

movies_oltp['title_lowercase'] = movies_oltp['title'].str.lower()
movies_oltp['releaseDate'] = movies_oltp['releaseDate'].astype(str)
movies_oltp['AwardMovie'] = "Sin Info"
movies_oltp = movies_oltp.rename(columns={"title":"movieTitle"})
movies_oltp = movies_oltp.drop(columns=["movieID"])

print(movies_oltp.shape)
print(movies_oltp.columns)

(58, 7)
Index(['movieTitle', 'releaseDate', 'genre', 'participantName',
       'performerRole', 'title_lowercase', 'AwardMovie'],
      dtype='object')

## merging dataframes

In [9]:
movies_columns = ['movieTitle', 'genre', 'releaseDate', 'AwardMovie','title_lowercase']
df_movies = pd.concat([movies[movies_columns], movies_oltp[movies_columns]], ignore_index=True, axis=0)

print(df_movies.shape)
print(df_movies.columns)

(9183, 5)
Index(['movieTitle', 'genre', 'releaseDate', 'AwardMovie', 'title_lowercase'], dtype='object')

In [10]:
df_movies = df_movies.merge(interactions,on="title_lowercase",how="left")
df_movies = df_movies.drop(columns="movieTitle_y").rename(columns={"movieTitle_x":"movieTitle"})
df_movies.reset_index(names='movieIndex', inplace=True)

print(df_movies.shape)
print(df_movies.columns)

(9713, 12)
Index(['movieIndex', 'movieTitle', 'genre', 'releaseDate', 'AwardMovie',
       'title_lowercase', 'user', 'finishCount', 'backClickCount',
       'movieForwardCount', 'playCount', 'movieViewPercentage'],
      dtype='object')

,movieIndex,movieTitle,genre,releaseDate,AwardMovie,title_lowercase,user,finishCount,backClickCount,movieForwardCount,playCount,movieViewPercentage
0,0,"Birth of a Nation, The",Drama,1915-01-01,Sin Info,"birth of a nation, the",user_26,2.0,1.0,3.0,1.0,61.63
1,1,"Immigrant, The",Comedy,1917-01-01,Sin Info,"immigrant, the",user_17,2.0,1.0,1.0,1.0,100.00
2,2,"Immigrant, The",Comedy,1917-01-01,Sin Info,"immigrant, the",user_17,5.0,1.0,2.0,0.0,100.00
3,3,"Cabinet of Dr. Caligari, The (Cabinet des Dr. ...",Crime,1920-01-01,Sin Info,"cabinet of dr. caligari, the (cabinet des dr. ...",user_6,1.0,1.0,3.0,2.0,100.00
4,4,"Mark of Zorro, The",Adventure,1920-01-01,Sin Info,"mark of zorro, the",user_20,2.0,1.0,1.0,2.0,62.11
5,5,"Mark of Zorro, The",Adventure,1920-01-01,Sin Info,"mark of zorro, the",user_15,1.0,1.0,0.0,1.0,100.00
6,6,"Haunted House, The",Comedy,1921-01-01,Sin Info,"haunted house, the",user_3,2.0,1.0,2.0,6.0,100.00
7,7,Nanook of the North,Documentary,1922-01-01,Grammy,nanook of the north,user_18,1.0,9.0,0.0,3.0,100.00
8,8,Cops,Comedy,1922-01-01,Oscar,cops,user_28,1.0,2.0,2.0,0.0,67.58
9,9,Sherlock Jr.,Comedy,1924-01-01,Sin Info,sherlock jr.,user_29,2.0,8.0,4.0,2.0,100.00
10,10,Seven Chances,Comedy,1925-01-01,Sin Info,seven chances,user_3,2.0,1.0,0.0,4.0,100.00
11,11,"Gold Rush, The",Adventure,1925-01-01,Sin Info,"gold rush, the",user_21,1.0,2.0,3.0,1.0,100.00
12,12,Battleship Potemkin,Drama,1925-01-01,Grammy,battleship potemkin,user_9,1.0,0.0,0.0,2.0,100.00
13,13,"Lost World, The",Adventure,1925-01-01,Sin Info,"lost world, the",user_18,1.0,0.0,0.0,0.0,100.00
14,14,"Phantom of the Opera, The",Drama,1925-01-01,Oscar,"phantom of the opera, the",user_28,3.0,5.0,1.0,2.0,78.72
15,15,"Phantom of the Opera, The",Drama,1925-01-01,Oscar,"phantom of the opera, the",user_12,1.0,7.0,3.0,6.0,100.00
16,16,"Phantom of the Opera, The",Drama,1925-01-01,Oscar,"phantom of the opera, the",user_29,2.0,0.0,1.0,2.0,39.22
17,17,The Great Gatsby,Drama,1926-01-01,Grammy,the great gatsby,user_9,2.0,1.0,1.0,1.0,4.98
18,18,College,Comedy,1927-01-01,Grammy,college,user_29,2.0,1.0,2.0,3.0,14.01
19,19,"Passion of Joan of Arc, The (Passion de Jeanne...",Drama,1928-01-01,Oscar,"passion of joan of arc, the (passion de jeanne...",user_5,2.0,1.0,4.0,3.0,50.77

so now:
-df_movies: has movies, interactinos and users
-movies has scores
-movies_oltp has performers info

## movies dimention

In [11]:
import uuid

def generate_uuid():
    return str(uuid.uuid4().hex[:8].upper())

# dataframe containing information fetched from mongo
df_dim_movies = df_movies[["title_lowercase","movieTitle", "genre","releaseDate","AwardMovie"]].copy()
df_dim_movies["movieID"] = [generate_uuid() for _ in range(len(df_dim_movies))]
df_dim_movies = df_dim_movies.rename(columns={"AwardMovie":"award","movieTitle":"title"})

print(df_dim_movies.shape)
df_dim_movies.head()

(9713, 6)
                                     title_lowercase  \
0                            birth of a nation, the
1                                    immigrant, the
2                                    immigrant, the
3  cabinet of dr. caligari, the (cabinet des dr. ...
4                                mark of zorro, the

                                          movieTitle      genre releaseDate  \
0                            Birth of a Nation, The       Drama  1915-01-01
1                                    Immigrant, The      Comedy  1917-01-01
2                                    Immigrant, The      Comedy  1917-01-01
3  Cabinet of Dr. Caligari, The (Cabinet des Dr. ...      Crime  1920-01-01
4                                Mark of Zorro, The   Adventure  1920-01-01

      award   movieID
0  Sin Info  DF5B21D9
1  Sin Info  1F0E32CB
2  Sin Info  1E1A6123
3  Sin Info  6295AD07
4  Sin Info  CCF2599F

## get users dimention

In [12]:
df_dim_users = df_movies[["movieIndex","title_lowercase","user"]].copy()
df_dim_users = df_dim_users.rename(columns={"user": "username","movieIndex":"userID"})

print(df_dim_users.shape)
df_dim_users.head()

(9713, 3)

   userID                                    title_lowercase username
0       0                            birth of a nation, the   user_26
1       1                                    immigrant, the   user_17
2       2                                    immigrant, the   user_17
3       3  cabinet of dr. caligari, the (cabinet des dr. ...   user_6
4       4                                mark of zorro, the   user_20

## get interactions dimention

In [13]:
df_dim_interactions = df_movies[['movieIndex',"title_lowercase",'finishCount', 'backClickCount', 'movieForwardCount','playCount', 'movieViewPercentage']].copy()
df_dim_interactions = df_dim_interactions.rename(columns={"movieIndex":"interactionID"})

df_dim_interactions.head()

,interactionID,title_lowercase,finishCount,backClickCount,movieForwardCount,playCount,movieViewPercentage
0,0,"birth of a nation, the",2.0,1.0,3.0,1.0,61.63
1,1,"immigrant, the",2.0,1.0,1.0,1.0,100.00
2,2,"immigrant, the",5.0,1.0,2.0,0.0,100.00
3,3,"cabinet of dr. caligari, the (cabinet des dr. ...",1.0,1.0,3.0,2.0,100.00
4,4,"mark of zorro, the",2.0,1.0,1.0,2.0,62.11

## performers dimention

In [14]:
df_dim_performers = movies_oltp[["title_lowercase","participantName","performerRole"]].copy()
df_dim_performers = df_dim_performers.reset_index(names="performerID")
df_dim_performers.rename(columns={
  "participantName":"name",
  "performerRole":"role",
}, inplace=True)

print(df_dim_performers.shape)
print(df_dim_performers.columns)

(58, 4)
Index(['performerID', 'title_lowercase', 'name', 'role'], dtype='object')

## score dimention

In [15]:
df_dim_score = movies[["title_lowercase","movieTitle",'netflix_score','imdb_score', 'sensacine_score', 'rottentomatoes_score']].copy()

# merge duplicated values keeping the maximum score if two movies have the same title and different scores
df_dim_score = movies.groupby('title_lowercase').agg({
    'netflix_score': 'max',
    'imdb_score': 'max',
    'sensacine_score': 'max',
    'rottentomatoes_score': 'max'
}).reset_index()

# rename columns
df_dim_score.rename(columns={
    'netflix_score': 'netflixScore',
    'imdb_score': 'imdbScore',
    'sensacine_score': 'sensacineScore',
    'rottentomatoes_score': 'rottentomatoesScore'
},inplace=True)

df_dim_score = df_dim_score.reset_index(names="scoreID")

print(df_dim_score.shape)
print(df_dim_score.columns)

(8890, 6)
Index(['scoreID', 'title_lowercase', 'netflixScore', 'imdbScore',
       'sensacineScore', 'rottentomatoesScore'],
      dtype='object')

# LOAD STAGE

In [16]:
# check last movie id to avoid duplicated primary key error
query_last_movie_id = """
SELECT MAX(movieID) FROM dimmovie;
"""

last_movie_id_prefix = pd.read_sql(query_last_movie_id, con=dw_engine).iloc[0,0]
if last_movie_id_prefix is not None:
  df_dim_movies["movieID"] = last_movie_id_prefix + df_dim_movies["movieID"].astype(str)

# Load dimMovie data
dim_columns=["movieID", "genre","releaseDate","award"]
df_dim_movies[dim_columns].to_sql('dimmovie', con=dw_engine, if_exists='append', index=False)

9713

In [17]:
query_last_user_id = """
SELECT MAX(userID) FROM dimuser;
"""

df_dim_users["userID"] = df_dim_users["userID"].astype(int)

last_user_id = pd.read_sql(query_last_user_id, con=dw_engine).iloc[0, 0]
if last_user_id is not None:
  last_user_id = int(last_user_id)
  df_dim_users["userID"] = df_dim_users["userID"] + last_user_id + 1

# Load dimUser data
dim_columns = ["userID","username"]
df_dim_users[dim_columns].to_sql('dimuser', con=dw_engine, if_exists='append', index=False)

9713

In [18]:
query_last_interaction_id = """
SELECT MAX(interactionID) FROM diminteraction;
"""

df_dim_interactions["interactionID"] = df_dim_interactions["interactionID"].astype(int)

last_interaction_id = pd.read_sql(query_last_interaction_id, con=dw_engine).iloc[0, 0]
if last_interaction_id is not None:
  last_interaction_id = int(last_interaction_id)
  df_dim_interactions["interactionID"] = df_dim_interactions["interactionID"] + last_interaction_id + 1


# Load dimInteraction data
dim_columns = ['interactionID','finishCount', 'backClickCount', 'movieForwardCount','playCount', 'movieViewPercentage']
df_dim_interactions[dim_columns].to_sql('diminteraction', con=dw_engine, if_exists='append', index=False)

9713

In [19]:
query_last_score_id = """
SELECT MAX(scoreID) FROM dimscore;
"""

df_dim_score["scoreID"] = df_dim_score["scoreID"].astype(int)

last_score_id = pd.read_sql(query_last_score_id, con=dw_engine).iloc[0, 0]
if last_score_id is not None:
  last_score_id = int(last_score_id)
  df_dim_score["scoreID"] = df_dim_score["scoreID"] + last_score_id + 1

# Load dimScore data
dim_columns=["scoreID","netflixScore","imdbScore","sensacineScore","rottentomatoesScore"]
df_dim_score[dim_columns].to_sql('dimscore', con=dw_engine, if_exists='append', index=False)

8890

In [20]:
query_last_performer_id = """
SELECT MAX(performerID) FROM dimperformer;
"""

df_dim_performers["performerID"] = df_dim_performers["performerID"].astype(int)

last_performer_id = pd.read_sql(query_last_performer_id, con=dw_engine).iloc[0, 0]
if last_performer_id is not None:
  last_performer_id = int(last_performer_id)
  df_dim_performers["performerID"] = df_dim_performers["performerID"] + last_performer_id + 1

# Load performers data
dim_columns=["performerID","name","role"]
df_dim_performers[dim_columns].to_sql('dimperformer', con=dw_engine, if_exists='append', index=False)

58

## prepare fact watch

### map movies

In [22]:
df_fact_watchs = df_dim_movies[['movieID','title_lowercase']].copy()

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9713, 2)
    movieID                                    title_lowercase
0  DF5B21D9                            birth of a nation, the
1  1F0E32CB                                    immigrant, the
2  1E1A6123                                    immigrant, the
3  6295AD07  cabinet of dr. caligari, the (cabinet des dr. ...
4  CCF2599F                                mark of zorro, the

Index(['movieID', 'title_lowercase'], dtype='object')

### map performers

In [28]:
df_fact_watchs = df_fact_watchs.merge(df_dim_performers[["performerID","title_lowercase"]], on="title_lowercase", how="left")

print(df_fact_watchs.shape)
df_fact_watchs.columns

(9769, 3)

Index(['movieID', 'title_lowercase', 'performerID'], dtype='object')

In [ ]:
# df_fact_watchs = df_fact_watchs.merge(df_dim_performers[["performerID","title_lowercase"]], on="title_lowercase", how="left")

# print(df_fact_watchs.shape)
# df_fact_watchs.columns

### map interactions

In [31]:
df_fact_watchs = df_fact_watchs.merge(df_dim_interactions[['interactionID','title_lowercase']], on='title_lowercase', how='left')

print(df_fact_watchs.shape)
df_fact_watchs.columns

(15077, 4)

Index(['movieID', 'title_lowercase', 'performerID', 'interactionID'], dtype='object')

### map users

In [33]:
df_fact_watchs= df_fact_watchs.merge(df_dim_users[["userID","title_lowercase"]], on="title_lowercase",how='left')

print(df_fact_watchs.shape)
df_fact_watchs.columns

(89365, 5)

Index(['movieID', 'title_lowercase', 'performerID', 'interactionID', 'userID'], dtype='object')

### score

In [37]:
df_fact_watchs = df_fact_watchs.merge(df_dim_score[["scoreID","title_lowercase"]], on='title_lowercase',how='left')

print(df_fact_watchs.shape)
df_fact_watchs.columns

(89365, 6)

Index(['movieID', 'title_lowercase', 'performerID', 'interactionID', 'userID',
       'scoreID'],
      dtype='object')

load fact watch

In [38]:
# Prepare FactWatchs DataFrame
df_fact_watchs = df_fact_watchs[['userID', 'movieID','interactionID','performerID','scoreID']]
df_fact_watchs.reset_index(names='id', inplace=True)

# Load FactWatchs data
df_fact_watchs.to_sql('factwatchs', con=dw_engine, if_exists='append', index=False)

print("Data loaded successfully")

Data loaded successfully